name: 'kaizen'
description: 'Suggest small improvements continuously'
inputs:
  openai-api-token:
    description: Token for using the OpenAI API
    required: true
  github-token:
    description: GitHub token for creating PRs
    required: false
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "zap"
  color: "red"