name: 'kaizen'
description: 'Suggest small improvements continuously'
inputs:
  openai-api-token:
    description: Token for using the OpenAI API
    required: true
  github-token:
    description: GitHub token for creating PRs
    required: true
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'docker://ghcr.io/ethan42/kaizen:0.1.4'
  env:
    OPENAI_API_TOKEN: ${{ inputs.openai-api-token }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
branding:
  icon: "zap"
  color: "red"