name: 'kaizen'
description: 'Suggest small improvements continuously'
inputs:
  openai-api-token:
    description: Token for using the OpenAI API
    required: true
  github-token:
    description: GitHub token for creating PRs
    required: false
    default: ${{ github.token }}
  version:
    description: Version of the package
    required: true
    default: '0.1.0'
runs:
  using: 'docker'
  image: 'ghcr.io/ethan42/kaizen:0.1.0'
branding:
  icon: "zap"
  color: "red"