name: Kaizen

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Echo hello
      run: echo hello

    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: List files
      run: ls -altr .
