on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Echo hello
      run: echo hello

    - name: List files
      run: ls -altr .
