name: kaizen

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run kaizen
      uses: ethan42/kaizen@main
      with:
        openai-api-token: ${{ secrets.OPENAI_API_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version: '0.1.0'
